### ISSUE TITLE
release BMThingCLIWidgetDefinitionDownloader 2.1.0 contains an old version of the UIDefinitionProvider.js script

### ISSUE THREAD

**Issue by kklorenzotesta** [BogdanMihaiciuc/ThingCLI#39]
The zip in github release contains a version of the script that is not aligned with the one on master, in particular the version in the zip doesn't excludes the "ptcschartcombo","ptcschartpie" and "dataexportfunction" widgets, whose definitions are now included in the latest version of the bm-thing-cli, causing builds to fail on Thingworx 9.4 for duplicate definitions after the generation.
The solution is simply to create a new release with the correct files from master.

**Comment by BogdanMihaiciuc** [comment]
Thank you for reporting this, I will get it fixed over the weekend

**Comment by BogdanMihaiciuc** [comment]
This should be resolved with the 2.1.1 release.
